
	export const Quote = [
		"Remember, if you smoke after sex you're doing it too fast.",
		"Is sex dirty? Only if it is done right.",
		"Having sex is like playing bridge. If you don't have a good partner, you'd better have a good hand.",
		"Love is the answer, but while you are waiting for the answer, sex raises some pretty good questions.",
		"Sex between a man and a woman can be absolutely wonderful - provided you get between the right man and the right woman.",
		"Sex is the most fun you can have without laughing.",
		"The difference between sex and death is, with death you can do it alone and nobody's going to make fun of you.",
		"Sex is better than talk...Talk is what you suffer through so you can get to sex.",
		"Sex is like having dinner: sometimes you joke about the dishes, sometimes you take the meal seriously.",
		"I don't know the question, but sex is definitely the answer.",
		"In my house I'm the boss, my wife is just the decision maker.",
		"Bisexuality doubles your chances of a date on a Saturday night.",
		"I'm such a good lover because I practice a lot on my own.",
		"Don't knock masturbation - it's sex with someone I love.",
		"I believe that sex is a beautiful thing between two people. Between five, it's fantastic.",
		"I think sex is better than logic, but I can't prove it.",
		"I'd like to meet the man who invented sex and see what he's working on now.",
		"Love is a matter of chemistry, but sex is a matter of physics.",
		"An intellectual is someone who has found something more interesting than sex.",
		"The major civilizing force in the world is not religion, it is sex.",
		"I read so many bad things about sex that I had to give up reading.",
		"If sex is such a natural phenomenon, how come there are so many books on how to do it?",
		"Great food is like great sex -the more you have the more you want.",
		"For me, love is very deep, but sex only has to go a few inches.",
		"Men get laid, but women get screwed.",
		"Women need a reason to have sex. Men just need a place.",
		"Sex is a short cut to everything.",
		"Sex is God's joke on human beings.",
		"Sex is two plus two making five, rather than four. Sex is the X ingredient that you can't define, and it's that X ingredient between two people that make both a man and a woman good in bed. It's all relative. There are no rules.",
		"Why did God give us genitals if he wanted us to think clearly.",
		"Sex is the gateway to life.",
		"God created the flirt as soon as he made the fool.",
		"Life is a sexually transmitted disease.",
		"The tragedy is when you've got sex in the head instead of down where it belongs.",
		"If God considers sex as sin, then there is no greater sinner than God.",
		"A woman's appetite is twice that of a man's; her sexual desire, four times; her intelligence, eight times.",
		"Making love? It's a communion with a woman. The bed is the holy table. There I find passion and purification.",
		"She embraces him with such force that their bodies become a single body.",
		"A woman never forgets the men she could have had; a man, the women he couldn't.",
		"If God didn't expect man to eat pussy.... why did he shape it like a TACO?"
	];